import { BrowserModule, Title } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AngularFontAwesomeModule } from 'angular-font-awesome';
import { NgxPageScrollModule } from 'ngx-page-scroll';

// *******************************************************************************
// NgBootstrap

import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

// *******************************************************************************
// App

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AppService } from './app.service';
import { LayoutModule } from './modules/layout/layout.module';

// *******************************************************************************
// Pages

import { HomeComponent } from './home/home.component';
import { Page2Component } from './page-2/page-2.component';

// *******************************************************************************
// HttpClient and custom interceptor

import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { HttpConfigInterceptor} from './core/interceptor/httpconfig.interceptor';

// *******************************************************************************
// Api Service
import { ApiService } from './core/services/api.service';

// *******************************************************************************
// Auth and user Service
import { AuthenticationService } from './core/services/authentication.service';
import { UserService } from './core/services/user.service';

// *******************************************************************************
// Global Service
import { GlobalsService } from './shared/globals.service';

// *******************************************************************************
// Perfect scroll bar npm package
import { PerfectScrollbarModule } from 'ngx-perfect-scrollbar';
import { PERFECT_SCROLLBAR_CONFIG } from 'ngx-perfect-scrollbar';
import { PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';

// *******************************************************************************
// Block UI npm package

import { BlockUIModule } from 'ng-block-ui';
import { BlockTemplateCmpComponent } from './shared/block-template-cmp/block-template-cmp.component';

// *******************************************************************************
// Auth Guard

import { AuthGuard } from './core/guard/auth.guard';

import { FakeBackendInterceptor } from './core/interceptor/fakeBackend.interceptor';

import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';


import { FrameworkHttpClientService } from './core/http/framework-http-client.service';
import { BaseHttpClientService } from './core/http/base-http-client.service';
import { SessionService } from './core/services/session.service';


import { CalendarModule, DateAdapter } from 'angular-calendar';

import {ToastrModule} from 'ngx-toastr';
import { AvatarTextPipe } from './shared/pipe/avatar-text.pipe';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';

const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};

@NgModule({

  declarations: [
    AppComponent,

    // Pages
    HomeComponent,
    Page2Component,
    BlockTemplateCmpComponent,
    AutoGeneratedComponent
  ],

  imports: [
    BrowserModule,
    NgbModule.forRoot(),
    HttpClientModule,
    BrowserAnimationsModule,
    AngularFontAwesomeModule,
    // App
    AppRoutingModule,
    LayoutModule,
    PerfectScrollbarModule,
    FormsModule,
    ToastrModule.forRoot({
      timeOut: 3000,
      tapToDismiss: true,
      toastClass: 'ngx-toastr',
      positionClass: 'toast-top-right',
      preventDuplicates: true}),
    BlockUIModule.forRoot({template: BlockTemplateCmpComponent}),
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory
    }),
    NgxPageScrollModule
  ],

  providers: [
    AvatarTextPipe,
    Title,
    AppService,
    ApiService,
    AuthenticationService,
    UserService,
    GlobalsService,
    FrameworkHttpClientService,
    BaseHttpClientService,
    SessionService,
    AuthGuard,
    { provide: HTTP_INTERCEPTORS, useClass: HttpConfigInterceptor, multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: FakeBackendInterceptor , multi: true},
    { provide: PERFECT_SCROLLBAR_CONFIG, useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG }
  ],

  bootstrap: [
    AppComponent
  ],
  entryComponents: [ BlockTemplateCmpComponent ],


})
export class AppModule {}
